# Generated by Django 4.0.3 on 2022-03-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posttag',
            field=models.ManyToManyField(blank=True, default=None, to='blog.tag'),
        ),
    ]
