# Generated by Django 4.0.3 on 2022-03-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posttag',
            field=models.ManyToManyField(blank=True, default=None, related_name='tags', to='blog.tag'),
        ),
    ]
