# Generated by Django 4.0.3 on 2022-03-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tag_slug_alter_post_posttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
