# Generated by Django 3.2.11 on 2022-04-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220412_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
