# Generated by Django 3.2.11 on 2022-04-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_postcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='Comment',
        ),
    ]
